name: pre-commit

on:
  pull_request:
  push:
    branches: [master]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7
    - uses: pre-commit/action@v3.0.1
